### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by kojix2**
* Add a document badge
* Use `*` instead of `●`
* And minor fixes...

### CODE REVIEW

**Comment by kojix2** [comment]
I think you should probably delete the Development section. 
Your testing framework is minitest, but it says rspec...

**Comment by unagiootoro** [comment]
This change is easy to see and I think it's very good.

**Comment by unagiootoro** [comment]
>> Your testing framework is minitest, but it says rspec...

Where is it? I couldn't find it.

**Comment by kojix2** [comment]
Here.

> Then, run rake "spec" to run the tests. 

image

**Comment by unagiootoro** [comment]
Thank you.
Modify the corresponding part to'rake test'.
Leave the development section itself.

**Comment by kojix2** [comment]
I think you should delete the Development section because `bin` directories are usually removed.

For example

* https://github.com/yoshoku/rumale
* https://github.com/ruby-numo/numo-narray

There is no `bin` in these repositories. Okay?
This is just a convention, so you can leave `bin` directory if you like. 
But usually, they delete it.
One reason, I think, is that it looks like a directory for executables.

I will send you another PR...

**Pull request merged**
